# Generated by Django 5.1.4 on 2025-01-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
